channels:
- conda-forge
dependencies:
- python=3.10.4
- pip<=22.0.4
- pip:
  - mlflow
  - astunparse==1.6.3
  - cloudpickle==2.1.0
  - dill==0.3.5.1
  - ipython==8.4.0
  - torch==1.11.0
  - tqdm==4.64.0
name: mlflow-env
